import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import Link from "next/link"

import { TRPCReactProvider } from "@/trpc/react";


import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
  navigationMenuTriggerStyle,
} from "@/components/ui/navigation-menu"

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <NavigationMenu>
            <NavigationMenuList className="bg-secondary">
              <NavigationMenuItem className="bg-secondary">
                <Link href="/" legacyBehavior passHref>
                <NavigationMenuLink className={navigationMenuTriggerStyle()}>Home</NavigationMenuLink>
                </Link>
              </NavigationMenuItem>

              <NavigationMenuItem>
              <NavigationMenuTrigger>Evaluations</NavigationMenuTrigger>
              <NavigationMenuContent>
              <ul className="grid gap-3 p-6 md:w-[400px] lg:w-[500px] lg:grid-cols-[.75fr_1fr]">
                <li className="row-span-3">
                <NavigationMenuLink asChild>
                <a
                    className="flex h-full w-full select-none flex-col justify-end rounded-md bg-gradient-to-b from-muted/50 to-muted p-6 no-underline outline-none focus:shadow-md"
                    href="/eval"
                  >
                <div className="mb-2 mt-4 text-lg font-medium">
                  Evaluations
                </div>
                <p className="text-sm leading-tight text-muted-foreground">
                  See what we found about different Large Language Models
                </p>
                </a>
                </NavigationMenuLink>
                </li>
                </ul>
              </NavigationMenuContent>
              </NavigationMenuItem>

              <NavigationMenuItem>
              <NavigationMenuTrigger>Tools</NavigationMenuTrigger>
              <NavigationMenuContent>
              <ul className="grid gap-3 p-6 md:w-[400px] lg:w-[500px] lg:grid-cols-[.75fr_1fr]">
                <li className="row-span-3">
                <NavigationMenuLink asChild>
                <a
                    className="flex h-full w-full select-none flex-col justify-end rounded-md bg-gradient-to-b from-muted/50 to-muted p-6 no-underline outline-none focus:shadow-md"
                    href="/eval"
                  >
                <div className="mb-2 mt-4 text-lg font-medium">
                  Tools
                </div>
                <p className="text-sm leading-tight text-muted-foreground">
                  Look at the awesome tools that we have made for future projects
                </p>
                </a>
                </NavigationMenuLink>
                </li>
                </ul>
              </NavigationMenuContent>
              </NavigationMenuItem>
            </NavigationMenuList>
          </NavigationMenu>
          {children}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
